version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d  # <-- aquí puedes poner scripts .sql iniciales

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"  # phpMyAdmin en http://localhost:8080
    depends_on:
      - mysql

  api:
    build: .
    container_name: schoolnet_api
    restart: always
    env_file:
      - .env   # 👈 aquí, no ./api/.env
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  mysql_data:

