const yearsRoutes = require('../routes/years.route');
const teachingBlocksRoutes = require('../routes/teachingBlocks.route');
const holidaysRoutes = require('../routes/holidays.routes');
const teachingDaysRoutes = require('../routes/teachingDays.routes');
const coursesRoutes = require('../routes/courses.routes');
const gradesRoutes = require('../routes/grades.routes');
const sectionsRoutes = require('../routes/sections.routes');
const personsRoutes = require('../routes/persons.routes');
const usersRoutes = require('../routes/users.routes');
const teachersAssignmentsRoutes = require('../routes/teachersAssignments.routes');
const studentEnrollmentsRoutes = require('../routes/studentEnrollments.routes');
const representativeAssignments = require('../routes/representativesAssignments.routes');
const schedulesRoutes = require('../routes/schedules.routes');
const assistanceRoutes = require('../routes/assistances.routes');
const authRoutes = require('../routes/auth.routes');
const qualificationRoutes = require('../routes/qualifications.routes');
const examsRoutes = require('../routes/exams.routes');
const tBAvaragesRoutes = require('../routes/teachingBlockAverage.route');
const generalAverage = require('../routes/generalAverage.routes');
const incidentsRoutes = require('../routes/incidents.route');

module.exports = (app) => {
  app.use('/api', yearsRoutes);
  app.use('/api', teachingBlocksRoutes);
  app.use('/api', holidaysRoutes);
  app.use('/api', teachingDaysRoutes);
  app.use('/api', coursesRoutes);
  app.use('/api', gradesRoutes);
  app.use('/api', sectionsRoutes);
  app.use('/api', personsRoutes);
  app.use('/api', usersRoutes);
  app.use('/api', teachersAssignmentsRoutes);
  app.use('/api', studentEnrollmentsRoutes);
  app.use('/api', representativeAssignments);
  app.use('/api', schedulesRoutes);
  app.use('/api', assistanceRoutes);
  app.use('/api', qualificationRoutes);
  app.use('/api', examsRoutes);
  app.use('/api', tBAvaragesRoutes);
  app.use('/api', generalAverage);
  app.use('/api', incidentsRoutes);
};
